# terminal-beauty: Everforest
add_newline = true

format = """
[](#7fbbb3)\
$directory\
[](fg:#7fbbb3 bg:#d699b6)\
$git_branch\
$git_status\
[](fg:#d699b6 bg:#56635f)\
$cmd_duration\
[ ](fg:#56635f)\
$character"""

[directory]
style = "fg:#2d353b bg:#7fbbb3"
format = "[ $path ]($style)"
truncation_length = 3

[git_branch]
symbol = ""
style = "fg:#2d353b bg:#d699b6"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "fg:#2d353b bg:#d699b6"
format = "[$all_status$ahead_behind ]($style)"

[cmd_duration]
style = "fg:#d3c6aa bg:#56635f"
format = "[  $duration ]($style)"

[character]
success_symbol = "[❯](bold #a7c080)"
error_symbol = "[❯](bold #e67e80)"
